### ISSUE TITLE
Load nolp.ko

### ISSUE THREAD

**Issue by moul** [online-labs/initrd#25]
Also try to initialize GPIO from initrd

**Comment by kwizart** [comment]
Is there a way to have the nolp kernel module source code so it can be rebuilt for a standard fedora kernel ? Or at least to build a version of the nolp module for the kernel I plan to use,
which will be derived from an official fedora kernel. (with the missing patch and config options applied on top ).

Thx for the info

Nicolas (kwizart)
RPM Fusion projet coordinator.

**Comment by moul** [comment]
Yes, we are working on to get an open source version of the module; The blocking issues are more political than technical.

That's why I'm trying to write a workaround in the initrd that will mimics the module features.

**Comment by kwizart** [comment]
Thx for your answer, I've attempted to make a scratch build of the fedora kernel with the patches you are using applied:
http://koji.fedoraproject.org/koji/taskinfo?taskID=8939120 (still building)
https://fedorapeople.org/cgit/kwizart/public_git/kernel.git/log/?h=f21-3.18-armada

Unfortunately I don't have access to the support forum at online labs to continue discussing about that. (the confirmation email on my gmail account wasn't received).

**Comment by zx2c4** [comment]
> Yes, we are working on to get an open source version of the module; The blocking issues are more political than technical.

Was this eventually open-sourced with this?
https://github.com/scaleway/kernel-tools/blob/master/modules/scaleway-c1-soc-irq.c

Aside from function names, nolp.ko looks pretty similar to scaleway-c1-soc-irq.c.

**Comment by moul** [comment]
Good catch, this is one version of the nolp.ko kernel module, this version works for mainline kernel, we still don't have opensourced the one for Marvell LSP kernel
