### ISSUE TITLE
Setting argv[0][0] = '@' for xnbd-client

### ISSUE THREAD

**Issue by esmil** [online-labs/initrd#40]
In order to prevent the xnbd-client from being killed before the root filesystem is properly unmounted, you want to have it's first character of argv[0] set to '@' as described here:
http://www.freedesktop.org/wiki/Software/systemd/RootStorageDaemons/

In the Makefile a symlink /usr/sbin/@xnbd-client -> xnbd-client is created, so some thought must have gone into this already. Unfortunately this doesn't accomplish the task since it just means argv[0] is "/usr/sbin/@xnbd-client" (which has '/' as the first character).
In bash you can do
`(exec -a @nbd-client $NBD_CLIENT --blocksize .. 2>/dev/null)`
but since this is a busybox shell it probably doesn't work. Maybe something like
`(export PATH='/usr/sbin'; exec @xnbd-client --blocksize .. 2>/dev/null)`
will work with the symlink though.
Alternatively there is the chpst command from runit which has a -b command to set argv0, but this argument might also have been removed from chpst before including it in busybox.

**Comment by moul** [comment]
Thanks a lot for your recommendation, I will try your solutions and keep the working one

**Comment by esmil** [comment]
With all respect this is not an enhancement, but a bug. It prevents any systemd based distro from powering off or rebooting properly, and there is already support for it in the initrd, it just doesn't work. In other words: a bug.

In any case it would be nice to get fixed so systemd can get far enough to check if there is anything in /run/initramfs. This way I and others can experiment with putting stuff there to shut down the xnbd-client of the root filesystem properly before booting (as described in #31).

**Comment by moul** [comment]
dev-initrd-nbd:~# ps aux | grep xnbd
    660 root       0:00 @xnbd-client --blocksize 4096 --retry=900 10.1.44.110 4288 /dev/nbd0
