### ISSUE TITLE
Add a `boot=live` mode

### ISSUE THREAD

**Issue by moul** [online-labs/initrd#42]
- `boot=live`
- `live=auto` or `live=install`

**Comment by moul** [comment]
To create a server with "live" mode and "install from scratch" on each boots behaviour:
- use these tags `boot=live, live_mode=install, rescue_image=http://test-images.fr-1.storage.online.net/ocs-distrib-alpine-latest.tar`: will tags
- or just call `onlinelabs create 10GB --env="boot=live" --env="rescue_image=http://test-images.fr-1.storage.online.net/ocs-distrib-ubuntu-trusty.tar" --env="live_mode=install"`

To create a server with "live" mode and "automatic" behaviour:
- use these tags `boot=live, rescue_image=http://test-images.fr-1.storage.online.net/ocs-distrib-alpine-latest.tar`: will tags
- or just call `onlinelabs create 10GB --env="boot=live" --env="rescue_image=http://test-images.fr-1.storage.online.net/ocs-distrib-ubuntu-trusty.tar"`

**Comment by aimxhaisse** [comment]
:ok_hand:
